require("./js/lib/hammer");
require('./js/global');
require("./js/animate");
require('./js/input-field');
require('./js/modal');
require('./js/waves');
require('./js/sidenav');
require('./js/slide');
require("./js/pushpin");
